# Realm Self-Upgrade Job: Upgrade the agent with freshly built binary
name = "self-upgrade-agent"
job_type = "one-shot"

[runtime]
type = "native"
binary = "/usr/bin/bash"
args = ["-c", """
set -e
echo "=== Preparing self-upgrade ==="
chmod +x /tmp/assets/realm-linux-x86_64 || true
chmod +x /tmp/artifacts/realm-linux-x86_64 || true
ls -la /tmp/assets/realm-linux-x86_64 || true
ls -la /tmp/artifacts/realm-linux_x86_64 || true

echo "=== Performing self-upgrade via init ==="
# Prefer artifact path if present, else fall back to pre-staged attachment path
if [ -f /tmp/artifacts/realm-linux-x86_64 ]; then
  /tmp/artifacts/realm-linux-x86_64 init
elif [ -f /tmp/assets/realm-linux-x86_64 ]; then
  /tmp/assets/realm-linux-x86_64 init
else
  echo "No upgrade binary found in /tmp/artifacts or /tmp/assets" >&2
  exit 1
fi

echo "=== Verifying upgrade ==="
sleep 2
realm status
echo "=== Self-upgrade complete! ==="
"""]
memory_mb = 512

[execution]
working_dir = "/tmp"
timeout_minutes = 10

[targeting]
platform = "linux/x86_64"
# Target your specific server
peer_ids = ["12D3KooWNXg8GbGBoS3c2XpdbCJAEXM6TbDUphn6RPxCYZeGyrgw"]
