[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[lib]
name = "hello"
path = "src/lib.rs"

[dependencies]
wit-bindgen = { version = "0.24.0", default-features = false, features = ["macros" ] }

[features]
default = []
component = []

